# Generated by Django 2.1.7 on 2019-03-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField()),
                ('job_title', models.TextField()),
                ('location', models.TextField()),
                ('job_function', models.TextField()),
                ('employment_type', models.TextField()),
                ('company_industry', models.TextField()),
                ('seniority_level', models.TextField()),
                ('job_description', models.TextField()),
                ('logo', models.URLField()),
            ],
        ),
    ]
